/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as GovernmentJobsRouteImport } from './routes/government-jobs'
import { Route as HighestPayingEngineeringJobsRouteImport } from './routes/highest-paying-engineering-jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAccessRouteImport } from './routes/_authenticated/access'
import { Route as AuthenticatedAccessibilityRouteImport } from './routes/_authenticated/accessibility'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedDnaRouteImport } from './routes/_authenticated/dna'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedJudgingRouteImport } from './routes/_authenticated/judging'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedMentorshipRouteImport } from './routes/_authenticated/mentorship'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedSathiRouteImport } from './routes/_authenticated/sathi'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as CompetitionsCompetitionIdRouteImport } from './routes/competitions.$competitionId'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardFacultyRouteImport } from './routes/_authenticated/dashboard.faculty'
import { Route as AuthenticatedDashboardIndustryRouteImport } from './routes/_authenticated/dashboard.industry'
import { Route as AuthenticatedDashboardInstitutionRouteImport } from './routes/_authenticated/dashboard.institution'
import { Route as AuthenticatedDashboardStudentRouteImport } from './routes/_authenticated/dashboard.student'
import { Route as AuthenticatedEmployerAccessibilityRouteImport } from './routes/_authenticated/employer.accessibility'
import { Route as AuthenticatedEmployerApplicantsRouteImport } from './routes/_authenticated/employer.applicants'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer.company'
import { Route as AuthenticatedEmployerMessagesRouteImport } from './routes/_authenticated/employer.messages'
import { Route as AuthenticatedEmployerOpportunitiesRouteImport } from './routes/_authenticated/employer.opportunities'
import { Route as AuthenticatedFacultyStudentsRouteImport } from './routes/_authenticated/faculty.students'
import { Route as AuthenticatedInstitutionCohortsRouteImport } from './routes/_authenticated/institution.cohorts'
import { Route as AuthenticatedInstitutionOutcomesRouteImport } from './routes/_authenticated/institution.outcomes'
import { Route as AuthenticatedInstitutionPartnersRouteImport } from './routes/_authenticated/institution.partners'
import { Route as AuthenticatedInstitutionSkillDemandRouteImport } from './routes/_authenticated/institution.skill-demand'
import { Route as AuthenticatedInstitutionStudentsRouteImport } from './routes/_authenticated/institution.students'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn.$slug'
import { Route as AuthenticatedMockTestsIndexRouteImport } from './routes/_authenticated/mock-tests.index'
import { Route as AuthenticatedMockTestsSlugRouteImport } from './routes/_authenticated/mock-tests.$slug'
import { Route as AuthenticatedOrganiserCompetitionsRouteImport } from './routes/_authenticated/organiser.competitions'
import { Route as AuthenticatedSathiIndexRouteImport } from './routes/_authenticated/sathi.index'
import { Route as AuthenticatedSathiThreadIdRouteImport } from './routes/_authenticated/sathi.$threadId'
import { Route as ApiSathiChatRouteImport } from './routes/api/sathi/chat'
import { Route as ApiSathiTranscribeRouteImport } from './routes/api/sathi/transcribe'
import { Route as ApiPublicHooksCrawlResourcesRouteImport } from './routes/api/public/hooks/crawl-resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentJobsRoute = GovernmentJobsRouteImport.update({
  id: '/government-jobs',
  path: '/government-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HighestPayingEngineeringJobsRoute =
  HighestPayingEngineeringJobsRouteImport.update({
    id: '/highest-paying-engineering-jobs',
    path: '/highest-paying-engineering-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessibilityRoute =
  AuthenticatedAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDnaRoute = AuthenticatedDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJudgingRoute = AuthenticatedJudgingRouteImport.update({
  id: '/judging',
  path: '/judging',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorshipRoute = AuthenticatedMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSathiRoute = AuthenticatedSathiRouteImport.update({
  id: '/sathi',
  path: '/sathi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsCompetitionIdRoute =
  CompetitionsCompetitionIdRouteImport.update({
    id: '/competitions/$competitionId',
    path: '/competitions/$competitionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardFacultyRoute =
  AuthenticatedDashboardFacultyRouteImport.update({
    id: '/dashboard/faculty',
    path: '/dashboard/faculty',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndustryRoute =
  AuthenticatedDashboardIndustryRouteImport.update({
    id: '/dashboard/industry',
    path: '/dashboard/industry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardInstitutionRoute =
  AuthenticatedDashboardInstitutionRouteImport.update({
    id: '/dashboard/institution',
    path: '/dashboard/institution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentRoute =
  AuthenticatedDashboardStudentRouteImport.update({
    id: '/dashboard/student',
    path: '/dashboard/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerAccessibilityRoute =
  AuthenticatedEmployerAccessibilityRouteImport.update({
    id: '/employer/accessibility',
    path: '/employer/accessibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerApplicantsRoute =
  AuthenticatedEmployerApplicantsRouteImport.update({
    id: '/employer/applicants',
    path: '/employer/applicants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/employer/company',
    path: '/employer/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerMessagesRoute =
  AuthenticatedEmployerMessagesRouteImport.update({
    id: '/employer/messages',
    path: '/employer/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerOpportunitiesRoute =
  AuthenticatedEmployerOpportunitiesRouteImport.update({
    id: '/employer/opportunities',
    path: '/employer/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacultyStudentsRoute =
  AuthenticatedFacultyStudentsRouteImport.update({
    id: '/faculty/students',
    path: '/faculty/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionCohortsRoute =
  AuthenticatedInstitutionCohortsRouteImport.update({
    id: '/institution/cohorts',
    path: '/institution/cohorts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionOutcomesRoute =
  AuthenticatedInstitutionOutcomesRouteImport.update({
    id: '/institution/outcomes',
    path: '/institution/outcomes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionPartnersRoute =
  AuthenticatedInstitutionPartnersRouteImport.update({
    id: '/institution/partners',
    path: '/institution/partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionSkillDemandRoute =
  AuthenticatedInstitutionSkillDemandRouteImport.update({
    id: '/institution/skill-demand',
    path: '/institution/skill-demand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionStudentsRoute =
  AuthenticatedInstitutionStudentsRouteImport.update({
    id: '/institution/students',
    path: '/institution/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockTestsIndexRoute =
  AuthenticatedMockTestsIndexRouteImport.update({
    id: '/mock-tests/',
    path: '/mock-tests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMockTestsSlugRoute =
  AuthenticatedMockTestsSlugRouteImport.update({
    id: '/mock-tests/$slug',
    path: '/mock-tests/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganiserCompetitionsRoute =
  AuthenticatedOrganiserCompetitionsRouteImport.update({
    id: '/organiser/competitions',
    path: '/organiser/competitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSathiIndexRoute = AuthenticatedSathiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSathiRoute,
} as any)
const AuthenticatedSathiThreadIdRoute =
  AuthenticatedSathiThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedSathiRoute,
  } as any)
const ApiSathiChatRoute = ApiSathiChatRouteImport.update({
  id: '/api/sathi/chat',
  path: '/api/sathi/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSathiTranscribeRoute = ApiSathiTranscribeRouteImport.update({
  id: '/api/sathi/transcribe',
  path: '/api/sathi/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCrawlResourcesRoute =
  ApiPublicHooksCrawlResourcesRouteImport.update({
    id: '/api/public/hooks/crawl-resources',
    path: '/api/public/hooks/crawl-resources',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/experience': typeof ExperienceRoute
  '/government-jobs': typeof GovernmentJobsRoute
  '/highest-paying-engineering-jobs': typeof HighestPayingEngineeringJobsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/opportunities': typeof OpportunitiesRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/access': typeof AuthenticatedAccessRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/judging': typeof AuthenticatedJudgingRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/sathi': typeof AuthenticatedSathiRouteWithChildren
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/faculty': typeof AuthenticatedDashboardFacultyRoute
  '/dashboard/industry': typeof AuthenticatedDashboardIndustryRoute
  '/dashboard/institution': typeof AuthenticatedDashboardInstitutionRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/employer/accessibility': typeof AuthenticatedEmployerAccessibilityRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/employer/opportunities': typeof AuthenticatedEmployerOpportunitiesRoute
  '/faculty/students': typeof AuthenticatedFacultyStudentsRoute
  '/institution/cohorts': typeof AuthenticatedInstitutionCohortsRoute
  '/institution/outcomes': typeof AuthenticatedInstitutionOutcomesRoute
  '/institution/partners': typeof AuthenticatedInstitutionPartnersRoute
  '/institution/skill-demand': typeof AuthenticatedInstitutionSkillDemandRoute
  '/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/mock-tests/$slug': typeof AuthenticatedMockTestsSlugRoute
  '/organiser/competitions': typeof AuthenticatedOrganiserCompetitionsRoute
  '/sathi/$threadId': typeof AuthenticatedSathiThreadIdRoute
  '/api/sathi/chat': typeof ApiSathiChatRoute
  '/api/sathi/transcribe': typeof ApiSathiTranscribeRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/mock-tests/': typeof AuthenticatedMockTestsIndexRoute
  '/sathi/': typeof AuthenticatedSathiIndexRoute
  '/api/public/hooks/crawl-resources': typeof ApiPublicHooksCrawlResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/experience': typeof ExperienceRoute
  '/government-jobs': typeof GovernmentJobsRoute
  '/highest-paying-engineering-jobs': typeof HighestPayingEngineeringJobsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/opportunities': typeof OpportunitiesRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/access': typeof AuthenticatedAccessRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/judging': typeof AuthenticatedJudgingRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/faculty': typeof AuthenticatedDashboardFacultyRoute
  '/dashboard/industry': typeof AuthenticatedDashboardIndustryRoute
  '/dashboard/institution': typeof AuthenticatedDashboardInstitutionRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/employer/accessibility': typeof AuthenticatedEmployerAccessibilityRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/employer/opportunities': typeof AuthenticatedEmployerOpportunitiesRoute
  '/faculty/students': typeof AuthenticatedFacultyStudentsRoute
  '/institution/cohorts': typeof AuthenticatedInstitutionCohortsRoute
  '/institution/outcomes': typeof AuthenticatedInstitutionOutcomesRoute
  '/institution/partners': typeof AuthenticatedInstitutionPartnersRoute
  '/institution/skill-demand': typeof AuthenticatedInstitutionSkillDemandRoute
  '/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/mock-tests/$slug': typeof AuthenticatedMockTestsSlugRoute
  '/organiser/competitions': typeof AuthenticatedOrganiserCompetitionsRoute
  '/sathi/$threadId': typeof AuthenticatedSathiThreadIdRoute
  '/api/sathi/chat': typeof ApiSathiChatRoute
  '/api/sathi/transcribe': typeof ApiSathiTranscribeRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/mock-tests': typeof AuthenticatedMockTestsIndexRoute
  '/sathi': typeof AuthenticatedSathiIndexRoute
  '/api/public/hooks/crawl-resources': typeof ApiPublicHooksCrawlResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/community': typeof CommunityRoute
  '/experience': typeof ExperienceRoute
  '/government-jobs': typeof GovernmentJobsRoute
  '/highest-paying-engineering-jobs': typeof HighestPayingEngineeringJobsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/opportunities': typeof OpportunitiesRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/access': typeof AuthenticatedAccessRoute
  '/_authenticated/accessibility': typeof AuthenticatedAccessibilityRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/dna': typeof AuthenticatedDnaRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/judging': typeof AuthenticatedJudgingRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/mentorship': typeof AuthenticatedMentorshipRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/sathi': typeof AuthenticatedSathiRouteWithChildren
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/faculty': typeof AuthenticatedDashboardFacultyRoute
  '/_authenticated/dashboard/industry': typeof AuthenticatedDashboardIndustryRoute
  '/_authenticated/dashboard/institution': typeof AuthenticatedDashboardInstitutionRoute
  '/_authenticated/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/_authenticated/employer/accessibility': typeof AuthenticatedEmployerAccessibilityRoute
  '/_authenticated/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/_authenticated/employer/opportunities': typeof AuthenticatedEmployerOpportunitiesRoute
  '/_authenticated/faculty/students': typeof AuthenticatedFacultyStudentsRoute
  '/_authenticated/institution/cohorts': typeof AuthenticatedInstitutionCohortsRoute
  '/_authenticated/institution/outcomes': typeof AuthenticatedInstitutionOutcomesRoute
  '/_authenticated/institution/partners': typeof AuthenticatedInstitutionPartnersRoute
  '/_authenticated/institution/skill-demand': typeof AuthenticatedInstitutionSkillDemandRoute
  '/_authenticated/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/_authenticated/mock-tests/$slug': typeof AuthenticatedMockTestsSlugRoute
  '/_authenticated/organiser/competitions': typeof AuthenticatedOrganiserCompetitionsRoute
  '/_authenticated/sathi/$threadId': typeof AuthenticatedSathiThreadIdRoute
  '/api/sathi/chat': typeof ApiSathiChatRoute
  '/api/sathi/transcribe': typeof ApiSathiTranscribeRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/mock-tests/': typeof AuthenticatedMockTestsIndexRoute
  '/_authenticated/sathi/': typeof AuthenticatedSathiIndexRoute
  '/api/public/hooks/crawl-resources': typeof ApiPublicHooksCrawlResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/experience'
    | '/government-jobs'
    | '/highest-paying-engineering-jobs'
    | '/login'
    | '/mcp'
    | '/opportunities'
    | '/register'
    | '/roles'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/access'
    | '/accessibility'
    | '/applications'
    | '/assessment'
    | '/dna'
    | '/journey'
    | '/judging'
    | '/mentor'
    | '/mentorship'
    | '/messages'
    | '/onboarding'
    | '/practice'
    | '/roadmap'
    | '/sathi'
    | '/competitions/$competitionId'
    | '/resources/$slug'
    | '/competitions/'
    | '/resources/'
    | '/.lovable/oauth/consent'
    | '/dashboard/admin'
    | '/dashboard/faculty'
    | '/dashboard/industry'
    | '/dashboard/institution'
    | '/dashboard/student'
    | '/employer/accessibility'
    | '/employer/applicants'
    | '/employer/company'
    | '/employer/messages'
    | '/employer/opportunities'
    | '/faculty/students'
    | '/institution/cohorts'
    | '/institution/outcomes'
    | '/institution/partners'
    | '/institution/skill-demand'
    | '/institution/students'
    | '/learn/$slug'
    | '/mock-tests/$slug'
    | '/organiser/competitions'
    | '/sathi/$threadId'
    | '/api/sathi/chat'
    | '/api/sathi/transcribe'
    | '/dashboard/'
    | '/learn/'
    | '/mock-tests/'
    | '/sathi/'
    | '/api/public/hooks/crawl-resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/experience'
    | '/government-jobs'
    | '/highest-paying-engineering-jobs'
    | '/login'
    | '/mcp'
    | '/opportunities'
    | '/register'
    | '/roles'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/access'
    | '/accessibility'
    | '/applications'
    | '/assessment'
    | '/dna'
    | '/journey'
    | '/judging'
    | '/mentor'
    | '/mentorship'
    | '/messages'
    | '/onboarding'
    | '/practice'
    | '/roadmap'
    | '/competitions/$competitionId'
    | '/resources/$slug'
    | '/competitions'
    | '/resources'
    | '/.lovable/oauth/consent'
    | '/dashboard/admin'
    | '/dashboard/faculty'
    | '/dashboard/industry'
    | '/dashboard/institution'
    | '/dashboard/student'
    | '/employer/accessibility'
    | '/employer/applicants'
    | '/employer/company'
    | '/employer/messages'
    | '/employer/opportunities'
    | '/faculty/students'
    | '/institution/cohorts'
    | '/institution/outcomes'
    | '/institution/partners'
    | '/institution/skill-demand'
    | '/institution/students'
    | '/learn/$slug'
    | '/mock-tests/$slug'
    | '/organiser/competitions'
    | '/sathi/$threadId'
    | '/api/sathi/chat'
    | '/api/sathi/transcribe'
    | '/dashboard'
    | '/learn'
    | '/mock-tests'
    | '/sathi'
    | '/api/public/hooks/crawl-resources'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/community'
    | '/experience'
    | '/government-jobs'
    | '/highest-paying-engineering-jobs'
    | '/login'
    | '/mcp'
    | '/opportunities'
    | '/register'
    | '/roles'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/access'
    | '/_authenticated/accessibility'
    | '/_authenticated/applications'
    | '/_authenticated/assessment'
    | '/_authenticated/dna'
    | '/_authenticated/journey'
    | '/_authenticated/judging'
    | '/_authenticated/mentor'
    | '/_authenticated/mentorship'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/practice'
    | '/_authenticated/roadmap'
    | '/_authenticated/sathi'
    | '/competitions/$competitionId'
    | '/resources/$slug'
    | '/competitions/'
    | '/resources/'
    | '/.lovable/oauth/consent'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/faculty'
    | '/_authenticated/dashboard/industry'
    | '/_authenticated/dashboard/institution'
    | '/_authenticated/dashboard/student'
    | '/_authenticated/employer/accessibility'
    | '/_authenticated/employer/applicants'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/messages'
    | '/_authenticated/employer/opportunities'
    | '/_authenticated/faculty/students'
    | '/_authenticated/institution/cohorts'
    | '/_authenticated/institution/outcomes'
    | '/_authenticated/institution/partners'
    | '/_authenticated/institution/skill-demand'
    | '/_authenticated/institution/students'
    | '/_authenticated/learn/$slug'
    | '/_authenticated/mock-tests/$slug'
    | '/_authenticated/organiser/competitions'
    | '/_authenticated/sathi/$threadId'
    | '/api/sathi/chat'
    | '/api/sathi/transcribe'
    | '/_authenticated/dashboard/'
    | '/_authenticated/learn/'
    | '/_authenticated/mock-tests/'
    | '/_authenticated/sathi/'
    | '/api/public/hooks/crawl-resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ExperienceRoute: typeof ExperienceRoute
  GovernmentJobsRoute: typeof GovernmentJobsRoute
  HighestPayingEngineeringJobsRoute: typeof HighestPayingEngineeringJobsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  RegisterRoute: typeof RegisterRoute
  RolesRoute: typeof RolesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CompetitionsCompetitionIdRoute: typeof CompetitionsCompetitionIdRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiSathiChatRoute: typeof ApiSathiChatRoute
  ApiSathiTranscribeRoute: typeof ApiSathiTranscribeRoute
  ApiPublicHooksCrawlResourcesRoute: typeof ApiPublicHooksCrawlResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-jobs': {
      id: '/government-jobs'
      path: '/government-jobs'
      fullPath: '/government-jobs'
      preLoaderRoute: typeof GovernmentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highest-paying-engineering-jobs': {
      id: '/highest-paying-engineering-jobs'
      path: '/highest-paying-engineering-jobs'
      fullPath: '/highest-paying-engineering-jobs'
      preLoaderRoute: typeof HighestPayingEngineeringJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accessibility': {
      id: '/_authenticated/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AuthenticatedAccessibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dna': {
      id: '/_authenticated/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof AuthenticatedDnaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judging': {
      id: '/_authenticated/judging'
      path: '/judging'
      fullPath: '/judging'
      preLoaderRoute: typeof AuthenticatedJudgingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentorship': {
      id: '/_authenticated/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof AuthenticatedMentorshipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sathi': {
      id: '/_authenticated/sathi'
      path: '/sathi'
      fullPath: '/sathi'
      preLoaderRoute: typeof AuthenticatedSathiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$competitionId': {
      id: '/competitions/$competitionId'
      path: '/competitions/$competitionId'
      fullPath: '/competitions/$competitionId'
      preLoaderRoute: typeof CompetitionsCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/faculty': {
      id: '/_authenticated/dashboard/faculty'
      path: '/dashboard/faculty'
      fullPath: '/dashboard/faculty'
      preLoaderRoute: typeof AuthenticatedDashboardFacultyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/industry': {
      id: '/_authenticated/dashboard/industry'
      path: '/dashboard/industry'
      fullPath: '/dashboard/industry'
      preLoaderRoute: typeof AuthenticatedDashboardIndustryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/institution': {
      id: '/_authenticated/dashboard/institution'
      path: '/dashboard/institution'
      fullPath: '/dashboard/institution'
      preLoaderRoute: typeof AuthenticatedDashboardInstitutionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student': {
      id: '/_authenticated/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthenticatedDashboardStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/accessibility': {
      id: '/_authenticated/employer/accessibility'
      path: '/employer/accessibility'
      fullPath: '/employer/accessibility'
      preLoaderRoute: typeof AuthenticatedEmployerAccessibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/applicants': {
      id: '/_authenticated/employer/applicants'
      path: '/employer/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/messages': {
      id: '/_authenticated/employer/messages'
      path: '/employer/messages'
      fullPath: '/employer/messages'
      preLoaderRoute: typeof AuthenticatedEmployerMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/opportunities': {
      id: '/_authenticated/employer/opportunities'
      path: '/employer/opportunities'
      fullPath: '/employer/opportunities'
      preLoaderRoute: typeof AuthenticatedEmployerOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty/students': {
      id: '/_authenticated/faculty/students'
      path: '/faculty/students'
      fullPath: '/faculty/students'
      preLoaderRoute: typeof AuthenticatedFacultyStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/cohorts': {
      id: '/_authenticated/institution/cohorts'
      path: '/institution/cohorts'
      fullPath: '/institution/cohorts'
      preLoaderRoute: typeof AuthenticatedInstitutionCohortsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/outcomes': {
      id: '/_authenticated/institution/outcomes'
      path: '/institution/outcomes'
      fullPath: '/institution/outcomes'
      preLoaderRoute: typeof AuthenticatedInstitutionOutcomesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/partners': {
      id: '/_authenticated/institution/partners'
      path: '/institution/partners'
      fullPath: '/institution/partners'
      preLoaderRoute: typeof AuthenticatedInstitutionPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/skill-demand': {
      id: '/_authenticated/institution/skill-demand'
      path: '/institution/skill-demand'
      fullPath: '/institution/skill-demand'
      preLoaderRoute: typeof AuthenticatedInstitutionSkillDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/students': {
      id: '/_authenticated/institution/students'
      path: '/institution/students'
      fullPath: '/institution/students'
      preLoaderRoute: typeof AuthenticatedInstitutionStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-tests/': {
      id: '/_authenticated/mock-tests/'
      path: '/mock-tests'
      fullPath: '/mock-tests/'
      preLoaderRoute: typeof AuthenticatedMockTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-tests/$slug': {
      id: '/_authenticated/mock-tests/$slug'
      path: '/mock-tests/$slug'
      fullPath: '/mock-tests/$slug'
      preLoaderRoute: typeof AuthenticatedMockTestsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organiser/competitions': {
      id: '/_authenticated/organiser/competitions'
      path: '/organiser/competitions'
      fullPath: '/organiser/competitions'
      preLoaderRoute: typeof AuthenticatedOrganiserCompetitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sathi/': {
      id: '/_authenticated/sathi/'
      path: '/'
      fullPath: '/sathi/'
      preLoaderRoute: typeof AuthenticatedSathiIndexRouteImport
      parentRoute: typeof AuthenticatedSathiRoute
    }
    '/_authenticated/sathi/$threadId': {
      id: '/_authenticated/sathi/$threadId'
      path: '/$threadId'
      fullPath: '/sathi/$threadId'
      preLoaderRoute: typeof AuthenticatedSathiThreadIdRouteImport
      parentRoute: typeof AuthenticatedSathiRoute
    }
    '/api/sathi/chat': {
      id: '/api/sathi/chat'
      path: '/api/sathi/chat'
      fullPath: '/api/sathi/chat'
      preLoaderRoute: typeof ApiSathiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sathi/transcribe': {
      id: '/api/sathi/transcribe'
      path: '/api/sathi/transcribe'
      fullPath: '/api/sathi/transcribe'
      preLoaderRoute: typeof ApiSathiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crawl-resources': {
      id: '/api/public/hooks/crawl-resources'
      path: '/api/public/hooks/crawl-resources'
      fullPath: '/api/public/hooks/crawl-resources'
      preLoaderRoute: typeof ApiPublicHooksCrawlResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSathiRouteChildren {
  AuthenticatedSathiThreadIdRoute: typeof AuthenticatedSathiThreadIdRoute
  AuthenticatedSathiIndexRoute: typeof AuthenticatedSathiIndexRoute
}

const AuthenticatedSathiRouteChildren: AuthenticatedSathiRouteChildren = {
  AuthenticatedSathiThreadIdRoute: AuthenticatedSathiThreadIdRoute,
  AuthenticatedSathiIndexRoute: AuthenticatedSathiIndexRoute,
}

const AuthenticatedSathiRouteWithChildren =
  AuthenticatedSathiRoute._addFileChildren(AuthenticatedSathiRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute
  AuthenticatedAccessibilityRoute: typeof AuthenticatedAccessibilityRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedDnaRoute: typeof AuthenticatedDnaRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedJudgingRoute: typeof AuthenticatedJudgingRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedMentorshipRoute: typeof AuthenticatedMentorshipRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSathiRoute: typeof AuthenticatedSathiRouteWithChildren
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardFacultyRoute: typeof AuthenticatedDashboardFacultyRoute
  AuthenticatedDashboardIndustryRoute: typeof AuthenticatedDashboardIndustryRoute
  AuthenticatedDashboardInstitutionRoute: typeof AuthenticatedDashboardInstitutionRoute
  AuthenticatedDashboardStudentRoute: typeof AuthenticatedDashboardStudentRoute
  AuthenticatedEmployerAccessibilityRoute: typeof AuthenticatedEmployerAccessibilityRoute
  AuthenticatedEmployerApplicantsRoute: typeof AuthenticatedEmployerApplicantsRoute
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerMessagesRoute: typeof AuthenticatedEmployerMessagesRoute
  AuthenticatedEmployerOpportunitiesRoute: typeof AuthenticatedEmployerOpportunitiesRoute
  AuthenticatedFacultyStudentsRoute: typeof AuthenticatedFacultyStudentsRoute
  AuthenticatedInstitutionCohortsRoute: typeof AuthenticatedInstitutionCohortsRoute
  AuthenticatedInstitutionOutcomesRoute: typeof AuthenticatedInstitutionOutcomesRoute
  AuthenticatedInstitutionPartnersRoute: typeof AuthenticatedInstitutionPartnersRoute
  AuthenticatedInstitutionSkillDemandRoute: typeof AuthenticatedInstitutionSkillDemandRoute
  AuthenticatedInstitutionStudentsRoute: typeof AuthenticatedInstitutionStudentsRoute
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
  AuthenticatedMockTestsSlugRoute: typeof AuthenticatedMockTestsSlugRoute
  AuthenticatedOrganiserCompetitionsRoute: typeof AuthenticatedOrganiserCompetitionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedMockTestsIndexRoute: typeof AuthenticatedMockTestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedAccessibilityRoute: AuthenticatedAccessibilityRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedDnaRoute: AuthenticatedDnaRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedJudgingRoute: AuthenticatedJudgingRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedMentorshipRoute: AuthenticatedMentorshipRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSathiRoute: AuthenticatedSathiRouteWithChildren,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardFacultyRoute: AuthenticatedDashboardFacultyRoute,
  AuthenticatedDashboardIndustryRoute: AuthenticatedDashboardIndustryRoute,
  AuthenticatedDashboardInstitutionRoute:
    AuthenticatedDashboardInstitutionRoute,
  AuthenticatedDashboardStudentRoute: AuthenticatedDashboardStudentRoute,
  AuthenticatedEmployerAccessibilityRoute:
    AuthenticatedEmployerAccessibilityRoute,
  AuthenticatedEmployerApplicantsRoute: AuthenticatedEmployerApplicantsRoute,
  AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
  AuthenticatedEmployerMessagesRoute: AuthenticatedEmployerMessagesRoute,
  AuthenticatedEmployerOpportunitiesRoute:
    AuthenticatedEmployerOpportunitiesRoute,
  AuthenticatedFacultyStudentsRoute: AuthenticatedFacultyStudentsRoute,
  AuthenticatedInstitutionCohortsRoute: AuthenticatedInstitutionCohortsRoute,
  AuthenticatedInstitutionOutcomesRoute: AuthenticatedInstitutionOutcomesRoute,
  AuthenticatedInstitutionPartnersRoute: AuthenticatedInstitutionPartnersRoute,
  AuthenticatedInstitutionSkillDemandRoute:
    AuthenticatedInstitutionSkillDemandRoute,
  AuthenticatedInstitutionStudentsRoute: AuthenticatedInstitutionStudentsRoute,
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
  AuthenticatedMockTestsSlugRoute: AuthenticatedMockTestsSlugRoute,
  AuthenticatedOrganiserCompetitionsRoute:
    AuthenticatedOrganiserCompetitionsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedMockTestsIndexRoute: AuthenticatedMockTestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ExperienceRoute: ExperienceRoute,
  GovernmentJobsRoute: GovernmentJobsRoute,
  HighestPayingEngineeringJobsRoute: HighestPayingEngineeringJobsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  RegisterRoute: RegisterRoute,
  RolesRoute: RolesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CompetitionsCompetitionIdRoute: CompetitionsCompetitionIdRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiSathiChatRoute: ApiSathiChatRoute,
  ApiSathiTranscribeRoute: ApiSathiTranscribeRoute,
  ApiPublicHooksCrawlResourcesRoute: ApiPublicHooksCrawlResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
