/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as AuthenticatedAccessibilityRouteImport } from './routes/_authenticated/accessibility'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedDnaRouteImport } from './routes/_authenticated/dna'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardIndustryRouteImport } from './routes/_authenticated/dashboard.industry'
import { Route as AuthenticatedDashboardInstitutionRouteImport } from './routes/_authenticated/dashboard.institution'
import { Route as AuthenticatedDashboardStudentRouteImport } from './routes/_authenticated/dashboard.student'
import { Route as AuthenticatedEmployerApplicantsRouteImport } from './routes/_authenticated/employer.applicants'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer.company'
import { Route as AuthenticatedEmployerOpportunitiesRouteImport } from './routes/_authenticated/employer.opportunities'
import { Route as AuthenticatedFacultyStudentsRouteImport } from './routes/_authenticated/faculty.students'
import { Route as AuthenticatedInstitutionCohortsRouteImport } from './routes/_authenticated/institution.cohorts'
import { Route as AuthenticatedInstitutionOutcomesRouteImport } from './routes/_authenticated/institution.outcomes'
import { Route as AuthenticatedInstitutionPartnersRouteImport } from './routes/_authenticated/institution.partners'
import { Route as AuthenticatedInstitutionSkillDemandRouteImport } from './routes/_authenticated/institution.skill-demand'
import { Route as AuthenticatedInstitutionStudentsRouteImport } from './routes/_authenticated/institution.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessibilityRoute =
  AuthenticatedAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDnaRoute = AuthenticatedDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndustryRoute =
  AuthenticatedDashboardIndustryRouteImport.update({
    id: '/dashboard/industry',
    path: '/dashboard/industry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardInstitutionRoute =
  AuthenticatedDashboardInstitutionRouteImport.update({
    id: '/dashboard/institution',
    path: '/dashboard/institution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentRoute =
  AuthenticatedDashboardStudentRouteImport.update({
    id: '/dashboard/student',
    path: '/dashboard/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerApplicantsRoute =
  AuthenticatedEmployerApplicantsRouteImport.update({
    id: '/employer/applicants',
    path: '/employer/applicants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/employer/company',
    path: '/employer/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerOpportunitiesRoute =
  AuthenticatedEmployerOpportunitiesRouteImport.update({
    id: '/employer/opportunities',
    path: '/employer/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacultyStudentsRoute =
  AuthenticatedFacultyStudentsRouteImport.update({
    id: '/faculty/students',
    path: '/faculty/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionCohortsRoute =
  AuthenticatedInstitutionCohortsRouteImport.update({
    id: '/institution/cohorts',
    path: '/institution/cohorts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionOutcomesRoute =
  AuthenticatedInstitutionOutcomesRouteImport.update({
    id: '/institution/outcomes',
    path: '/institution/outcomes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionPartnersRoute =
  AuthenticatedInstitutionPartnersRouteImport.update({
    id: '/institution/partners',
    path: '/institution/partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionSkillDemandRoute =
  AuthenticatedInstitutionSkillDemandRouteImport.update({
    id: '/institution/skill-demand',
    path: '/institution/skill-demand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionStudentsRoute =
  AuthenticatedInstitutionStudentsRouteImport.update({
    id: '/institution/students',
    path: '/institution/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/industry': typeof AuthenticatedDashboardIndustryRoute
  '/dashboard/institution': typeof AuthenticatedDashboardInstitutionRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/opportunities': typeof AuthenticatedEmployerOpportunitiesRoute
  '/faculty/students': typeof AuthenticatedFacultyStudentsRoute
  '/institution/cohorts': typeof AuthenticatedInstitutionCohortsRoute
  '/institution/outcomes': typeof AuthenticatedInstitutionOutcomesRoute
  '/institution/partners': typeof AuthenticatedInstitutionPartnersRoute
  '/institution/skill-demand': typeof AuthenticatedInstitutionSkillDemandRoute
  '/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/industry': typeof AuthenticatedDashboardIndustryRoute
  '/dashboard/institution': typeof AuthenticatedDashboardInstitutionRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/opportunities': typeof AuthenticatedEmployerOpportunitiesRoute
  '/faculty/students': typeof AuthenticatedFacultyStudentsRoute
  '/institution/cohorts': typeof AuthenticatedInstitutionCohortsRoute
  '/institution/outcomes': typeof AuthenticatedInstitutionOutcomesRoute
  '/institution/partners': typeof AuthenticatedInstitutionPartnersRoute
  '/institution/skill-demand': typeof AuthenticatedInstitutionSkillDemandRoute
  '/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/_authenticated/accessibility': typeof AuthenticatedAccessibilityRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/dna': typeof AuthenticatedDnaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/industry': typeof AuthenticatedDashboardIndustryRoute
  '/_authenticated/dashboard/institution': typeof AuthenticatedDashboardInstitutionRoute
  '/_authenticated/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/_authenticated/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/opportunities': typeof AuthenticatedEmployerOpportunitiesRoute
  '/_authenticated/faculty/students': typeof AuthenticatedFacultyStudentsRoute
  '/_authenticated/institution/cohorts': typeof AuthenticatedInstitutionCohortsRoute
  '/_authenticated/institution/outcomes': typeof AuthenticatedInstitutionOutcomesRoute
  '/_authenticated/institution/partners': typeof AuthenticatedInstitutionPartnersRoute
  '/_authenticated/institution/skill-demand': typeof AuthenticatedInstitutionSkillDemandRoute
  '/_authenticated/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/opportunities'
    | '/register'
    | '/roles'
    | '/accessibility'
    | '/applications'
    | '/assessment'
    | '/dna'
    | '/onboarding'
    | '/roadmap'
    | '/dashboard/admin'
    | '/dashboard/industry'
    | '/dashboard/institution'
    | '/dashboard/student'
    | '/employer/applicants'
    | '/employer/company'
    | '/employer/opportunities'
    | '/faculty/students'
    | '/institution/cohorts'
    | '/institution/outcomes'
    | '/institution/partners'
    | '/institution/skill-demand'
    | '/institution/students'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/opportunities'
    | '/register'
    | '/roles'
    | '/accessibility'
    | '/applications'
    | '/assessment'
    | '/dna'
    | '/onboarding'
    | '/roadmap'
    | '/dashboard/admin'
    | '/dashboard/industry'
    | '/dashboard/institution'
    | '/dashboard/student'
    | '/employer/applicants'
    | '/employer/company'
    | '/employer/opportunities'
    | '/faculty/students'
    | '/institution/cohorts'
    | '/institution/outcomes'
    | '/institution/partners'
    | '/institution/skill-demand'
    | '/institution/students'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/opportunities'
    | '/register'
    | '/roles'
    | '/_authenticated/accessibility'
    | '/_authenticated/applications'
    | '/_authenticated/assessment'
    | '/_authenticated/dna'
    | '/_authenticated/onboarding'
    | '/_authenticated/roadmap'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/industry'
    | '/_authenticated/dashboard/institution'
    | '/_authenticated/dashboard/student'
    | '/_authenticated/employer/applicants'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/opportunities'
    | '/_authenticated/faculty/students'
    | '/_authenticated/institution/cohorts'
    | '/_authenticated/institution/outcomes'
    | '/_authenticated/institution/partners'
    | '/_authenticated/institution/skill-demand'
    | '/_authenticated/institution/students'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  RegisterRoute: typeof RegisterRoute
  RolesRoute: typeof RolesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accessibility': {
      id: '/_authenticated/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AuthenticatedAccessibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dna': {
      id: '/_authenticated/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof AuthenticatedDnaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/industry': {
      id: '/_authenticated/dashboard/industry'
      path: '/dashboard/industry'
      fullPath: '/dashboard/industry'
      preLoaderRoute: typeof AuthenticatedDashboardIndustryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/institution': {
      id: '/_authenticated/dashboard/institution'
      path: '/dashboard/institution'
      fullPath: '/dashboard/institution'
      preLoaderRoute: typeof AuthenticatedDashboardInstitutionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student': {
      id: '/_authenticated/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthenticatedDashboardStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/applicants': {
      id: '/_authenticated/employer/applicants'
      path: '/employer/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/opportunities': {
      id: '/_authenticated/employer/opportunities'
      path: '/employer/opportunities'
      fullPath: '/employer/opportunities'
      preLoaderRoute: typeof AuthenticatedEmployerOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty/students': {
      id: '/_authenticated/faculty/students'
      path: '/faculty/students'
      fullPath: '/faculty/students'
      preLoaderRoute: typeof AuthenticatedFacultyStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/cohorts': {
      id: '/_authenticated/institution/cohorts'
      path: '/institution/cohorts'
      fullPath: '/institution/cohorts'
      preLoaderRoute: typeof AuthenticatedInstitutionCohortsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/outcomes': {
      id: '/_authenticated/institution/outcomes'
      path: '/institution/outcomes'
      fullPath: '/institution/outcomes'
      preLoaderRoute: typeof AuthenticatedInstitutionOutcomesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/partners': {
      id: '/_authenticated/institution/partners'
      path: '/institution/partners'
      fullPath: '/institution/partners'
      preLoaderRoute: typeof AuthenticatedInstitutionPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/skill-demand': {
      id: '/_authenticated/institution/skill-demand'
      path: '/institution/skill-demand'
      fullPath: '/institution/skill-demand'
      preLoaderRoute: typeof AuthenticatedInstitutionSkillDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/students': {
      id: '/_authenticated/institution/students'
      path: '/institution/students'
      fullPath: '/institution/students'
      preLoaderRoute: typeof AuthenticatedInstitutionStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessibilityRoute: typeof AuthenticatedAccessibilityRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedDnaRoute: typeof AuthenticatedDnaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardIndustryRoute: typeof AuthenticatedDashboardIndustryRoute
  AuthenticatedDashboardInstitutionRoute: typeof AuthenticatedDashboardInstitutionRoute
  AuthenticatedDashboardStudentRoute: typeof AuthenticatedDashboardStudentRoute
  AuthenticatedEmployerApplicantsRoute: typeof AuthenticatedEmployerApplicantsRoute
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerOpportunitiesRoute: typeof AuthenticatedEmployerOpportunitiesRoute
  AuthenticatedFacultyStudentsRoute: typeof AuthenticatedFacultyStudentsRoute
  AuthenticatedInstitutionCohortsRoute: typeof AuthenticatedInstitutionCohortsRoute
  AuthenticatedInstitutionOutcomesRoute: typeof AuthenticatedInstitutionOutcomesRoute
  AuthenticatedInstitutionPartnersRoute: typeof AuthenticatedInstitutionPartnersRoute
  AuthenticatedInstitutionSkillDemandRoute: typeof AuthenticatedInstitutionSkillDemandRoute
  AuthenticatedInstitutionStudentsRoute: typeof AuthenticatedInstitutionStudentsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessibilityRoute: AuthenticatedAccessibilityRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedDnaRoute: AuthenticatedDnaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardIndustryRoute: AuthenticatedDashboardIndustryRoute,
  AuthenticatedDashboardInstitutionRoute:
    AuthenticatedDashboardInstitutionRoute,
  AuthenticatedDashboardStudentRoute: AuthenticatedDashboardStudentRoute,
  AuthenticatedEmployerApplicantsRoute: AuthenticatedEmployerApplicantsRoute,
  AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
  AuthenticatedEmployerOpportunitiesRoute:
    AuthenticatedEmployerOpportunitiesRoute,
  AuthenticatedFacultyStudentsRoute: AuthenticatedFacultyStudentsRoute,
  AuthenticatedInstitutionCohortsRoute: AuthenticatedInstitutionCohortsRoute,
  AuthenticatedInstitutionOutcomesRoute: AuthenticatedInstitutionOutcomesRoute,
  AuthenticatedInstitutionPartnersRoute: AuthenticatedInstitutionPartnersRoute,
  AuthenticatedInstitutionSkillDemandRoute:
    AuthenticatedInstitutionSkillDemandRoute,
  AuthenticatedInstitutionStudentsRoute: AuthenticatedInstitutionStudentsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  RegisterRoute: RegisterRoute,
  RolesRoute: RolesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
