ALTER TABLE public.opportunities
  ADD COLUMN IF NOT EXISTS is_inclusive_employer boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS accessibility_features text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS accessibility_note text;

INSERT INTO public.opportunities (title, organisation, type, location, mode, description, tags, stipend, deadline, is_published, is_inclusive_employer, accessibility_features, accessibility_note)
VALUES
  ('Accessibility QA Intern', 'InclusiveTech Labs', 'internship', 'Remote (India)', 'remote', 'Test web products against WCAG 2.2 with screen readers and keyboard-only flows. Training provided; no prior QA experience required.', ARRAY['Accessibility','QA','WCAG','Screen readers'], 'INR 20,000 / month', (CURRENT_DATE + 45), true, true, ARRAY['Fully remote','Screen reader friendly tooling','Flexible hours','Assistive tech allowance'], 'Interview can be conducted over chat or with a sign language interpreter on request.'),
  ('Junior Data Analyst (Divyangjan Hiring Drive)', 'Bharat Analytics', 'job', 'Pune, Maharashtra', 'hybrid', 'Entry-level analytics role as part of a dedicated inclusive hiring drive. Support dashboards, reporting and data quality checks.', ARRAY['SQL','Excel','Dashboards','Analytics'], 'INR 4.5-6 LPA', (CURRENT_DATE + 60), true, true, ARRAY['Step-free office access','Accessible washrooms','Transport allowance','Flexible hours','Buddy mentor'], 'Reasonable accommodations are agreed before joining with the accessibility partner.'),
  ('Customer Support Associate — Sign Language Team', 'SevaConnect', 'job', 'Bengaluru, Karnataka', 'onsite', 'Support deaf and hard-of-hearing customers over video relay. ISL proficiency welcome; training available.', ARRAY['Communication','ISL','Support'], 'INR 3.6-4.8 LPA', (CURRENT_DATE + 30), true, true, ARRAY['ISL interpreter on site','Captioned meetings','Accessible venue','Quiet workspace'], 'All team meetings are captioned and interpreted.'),
  ('Assistive Technology Research Project', 'IIT Delhi Assistive Tech Lab', 'project', 'Remote (India)', 'remote', 'Semester-long student project building low-cost assistive devices and evaluating them with users.', ARRAY['Research','Hardware','Assistive tech','Prototyping'], 'Stipend on selection', (CURRENT_DATE + 25), true, true, ARRAY['Fully remote','Flexible hours','Screen reader friendly tooling','Extra time for tasks'], 'Mentors adapt project scope to each student''s working style.'),
  ('Inclusive Design Trainee', 'DesignForAll Studio', 'training', 'Hyderabad, Telangana', 'hybrid', 'Twelve-week paid training in inclusive and universal design, ending with a portfolio review.', ARRAY['Design','Figma','Inclusive design','Portfolio'], 'INR 15,000 / month', (CURRENT_DATE + 40), true, true, ARRAY['Step-free office access','Flexible hours','Captioned sessions','Assistive tech allowance','Remote days'], 'Studio sessions are recorded and captioned for later review.');